INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('67d7581d-4e10-4139-a446-05013a3c3cdd', 'aadhaar-pvc', 'Aadhaar PVC Smart Card', 100, 'Order a durable, wallet-sized, waterproof Aadhaar smart card printed on premium plastic (PVC) with UV protection.', 'Pocket-sized, waterproof Aadhaar smart card print with dynamic QR code.', '["Official Aadhaar PDF File (Downloaded from myAadhaar portal)","OR Aadhaar Number + OTP for download assistance"]', '["Wallet-sized (standard ATM size)","Vibrant high-definition colors","Scratch & water-resistant","Guaranteed barcode/QR code scan readability"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'identity', 1, 1, '2026-08-27T19:46:42.155Z', '2026-08-28T06:08:02.571Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('40716da7-a274-44bd-8240-e88dd494fabb', 'pan-pvc', 'PAN PVC Smart Card', 100, 'Get your Permanent Account Number printed on a premium glossy plastic PVC card. Convenient replacement for paper/faded cards.', 'Permanent Account Number printed on durable glossy plastic.', '["Official e-PAN Card PDF file","OR PAN Number + Date of Birth"]', '["Durable credit-card style layout","Glossy premium finish","Perfect color representation","Fits securely in wallets"]', '3 - 7 Days across India', '/images/pvc-pan-mockup.jpg', 'identity', 1, 1, '2026-08-27T19:46:42.158Z', '2026-08-28T06:08:02.578Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('da43afed-7038-4181-97db-60236f65d28e', 'ayushman-pvc', 'Ayushman Bharat PVC Card', 100, 'Make your PM-JAY Golden health card easy to carry in your wallet. Crucial for emergency hospital admissions.', 'PM-JAY Golden card on durable plastic for emergency hospital support.', '["Ayushman Golden Card PDF file","OR Beneficiary Family ID / Aadhaar"]', '["High durability for medical usage","Clear font rendering of Scheme details","Pocket-sized for immediate access","Glossy protection overlay"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'utility', 1, 1, '2026-08-27T19:46:42.161Z', '2026-08-28T06:08:02.583Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('2f1e4a1f-c13d-4103-9235-96b837fbb18a', 'voter-pvc', 'Voter ID PVC Smart Card', 100, 'Upgrade your old paper Voter Card to a modern, security-enabled PVC Smart Voter ID.', 'Upgrade your paper Voter ID card to a durable plastic smart card.', '["Voter ID PDF or EPIC Number","OR Voter card photo scan"]', '["Official standard dimensions","Enhanced durability","Readable election barcode","Dual-sided color printing"]', '3 - 7 Days across India', '/images/pvc-pan-mockup.jpg', 'identity', 1, 1, '2026-08-27T19:46:42.163Z', '2026-08-28T06:08:02.588Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('f8e2cb04-952b-4899-aa00-e7b87a5e52e6', 'driving-licence-pvc', 'Driving Licence PVC Card', 100, 'Convert your temporary virtual driving licence PDF into a robust, high-quality plastic card to show to authorities.', 'Premium plastic driving licence print matching official layouts.', '["Driving Licence PDF downloaded from Sarathi / DigiLocker","OR Driving Licence Number"]', '["Premium thick PVC material","High resolution typography","Official design alignment","Waterproof finish"]', '3 - 7 Days across India', '/images/pvc-pan-mockup.jpg', 'identity', 1, 0, '2026-08-27T19:46:42.166Z', '2026-08-28T06:08:02.595Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('34a5a5d6-b31c-4d6c-a99e-cbc2ffb1460b', 'rc-pvc', 'Vehicle RC PVC Smart Card', 100, 'Order a durable plastic duplicate of your Vehicle Registration Certificate (RC) for dashboard convenience.', 'Wallet-sized duplicate Registration Certificate for vehicle dashboards.', '["Registration Certificate PDF from Vahan / DigiLocker","OR Vehicle Registration Number"]', '["Double-sided high-contrast printing","Extremely long-lasting plastic","Durable in humid/hot glove boxes","Accurate official format"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'identity', 1, 0, '2026-08-27T19:46:42.169Z', '2026-08-28T06:08:02.600Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('23ec0bee-1b34-4a2e-bf8a-d0b5a3361386', 'e-shram-pvc', 'e-Shram PVC Card', 100, 'Get your e-Shram worker identification card printed on a durable, waterproof PVC smart card to easily carry to work sites and secure government benefits.', 'e-Shram card printed on premium plastic for unorganized sector workers.', '["e-Shram Card PDF downloaded from official portal","OR e-Shram registered phone number"]', '["High-contrast color print","Standard credit card size","Laminated moisture barrier","Heavy duty plastic build"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'utility', 1, 0, '2026-08-28T06:08:02.604Z', '2026-08-28T06:08:02.604Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('82fed3b0-b8a3-46c8-af22-c068ba904c7d', 'abha-pvc', 'ABHA Health ID PVC Card', 100, 'Print your Ayushman Bharat Health Account (ABHA) card on premium plastic. Convenient, wallet-sized, and long-lasting for easy hospital scans.', 'Ayushman Bharat Health Account Card printed on plastic.', '["ABHA Health Card PDF downloaded from ABHA portal","OR Health ID Number"]', '["Pocket-sized for medical emergencies","Accurate QR barcode reproduction","Waterproof glossy structure","Official alignment layouts"]', '3 - 7 Days across India', '/images/pvc-pan-mockup.jpg', 'utility', 1, 0, '2026-08-28T06:08:02.610Z', '2026-08-28T06:08:02.610Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('a5bc5f36-5433-49d6-b738-7fa47243ca53', 'udid-pvc', 'Unique Disability ID (UDID) PVC Card', 100, 'Convert your paper disability card into a wallet-sized, waterproof UDID smart card. Highly durable and convenient for obtaining travel and medical concessions.', 'Durable smart card duplicate of your disability identification.', '["UDID Card PDF or Certificate PDF","OR UDID Number details"]', '["Reinforced heavy plastic structure","Vibrant high-contrast visibility","Dual-sided official layouts","Waterproof and tearproof design"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'utility', 1, 0, '2026-08-28T06:08:02.616Z', '2026-08-28T06:08:02.616Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('b68f2d53-e86a-4106-bada-f3a0dd1ce012', 'ration-pvc', 'Ration Card PVC Print', 100, 'Get your digital ration card details printed onto a durable, easy-to-carry PVC plastic card for convenient usage at government ration shops.', 'Premium wallet-sized duplicate card for your family ration registry.', '["Ration Card PDF file or photo scan","OR Ration Card Number + District"]', '["ATM card size convenience","Readable ration dealer barcodes","Vibrant typography scaling","Waterproof glossy finish"]', '3 - 7 Days across India', '/images/pvc-pan-mockup.jpg', 'utility', 1, 0, '2026-08-28T06:08:02.623Z', '2026-08-28T06:08:02.623Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('ea30b919-733c-4a2e-a14f-17584ba8a824', 'uan-pvc', 'EPFO UAN PVC Smart Card', 100, 'Get your Universal Account Number (UAN) details printed on a glossy PVC smart card. Highly convenient for EPFO member verifications at bank branches and new offices.', 'Universal Account Number card on plastic for EPF members.', '["UAN Card PDF from Unified Member Portal","OR UAN Number details"]', '["ATM card dimensions template","Glossy wear-resistant laminate","Official EPFO green themes matching","Clear Member details rendering"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'utility', 1, 0, '2026-08-28T06:08:02.628Z', '2026-08-28T06:08:02.628Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('d910b15c-ee95-4f3d-b675-3a355fce4872', 'farmer-id-pvc', 'Farmer ID PVC Smart Card', 100, 'Print your PM-Kisan Farmer ID registry details onto a glossy, waterproof plastic smart card for easy presentation at local cooperative markets and seeds counters.', 'PM-Kisan identity card printed on durable plastic.', '["PM-Kisan registry summary or Farmer Certificate PDF","OR Farmer Registration ID"]', '["Extremely long-lasting plastic","Waterproof for agricultural environments","Official crop scheme credentials layout","ATM pocket-friendly shape"]', '3 - 7 Days across India', '/images/pvc-aadhaar-mockup.jpg', 'academic_others', 1, 0, '2026-08-28T06:08:02.633Z', '2026-08-28T06:08:02.633Z');
INSERT OR IGNORE INTO Product (id, slug, name, price, description, shortDescription, requirements, features, deliveryTime, image, category, active, featured, createdAt, updatedAt) VALUES ('de0da519-4f9f-4e62-937a-d108b31dc46c', 'student-id-pvc', 'Student ID PVC Card', 100, 'Convert your temporary paper student identity documents or school/college registry cards into a glossy, durable plastic card with sharp fonts.', 'Student identification details duplicated on a glossy smart card.', '["Student ID Card layout PDF or high-res photo scan","OR Admission form receipt with student photo"]', '["Vivid color rendering","Durable badge protection coating","Double-sided custom print matching","Free lanyard slot punch if requested"]', '3 - 7 Days across India', '/images/pvc-pan-mockup.jpg', 'academic_others', 1, 0, '2026-08-28T06:08:02.639Z', '2026-08-28T06:08:02.639Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('9ffac527-3fc3-4eaa-a801-9b06d862b641', 'new-pan-card-correction', 'New PAN Card & Correction', 'digital', '💳', 'Apply for a new Permanent Account Number (PAN) or make corrections to your existing PAN card details (name, DOB, photo, signature).', '["Aadhaar Card","2 Passport Size Photos","Active Mobile Number"]', '7 - 10 working days', 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html', 1, '2026-08-27T19:46:42.115Z', '2026-08-27T19:46:42.115Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('8048e0da-7f1e-4cfa-9d68-0a1b66031586', 'aadhaar-card-download-print', 'Aadhaar Card Download & Print', 'csc', '🆔', 'Get your official Aadhaar card downloaded and high-quality color prints on premium paper or smart cards.', '["Aadhaar Number or Enrolment ID","OTP sent to registered mobile"]', 'Instant (15 mins)', 'https://myaadhaar.uidai.gov.in/', 1, '2026-08-27T19:46:42.121Z', '2026-08-27T19:46:42.121Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('0ff96eae-f4c4-4339-8444-91ae6c0314fd', 'ayushman-bharat-golden-card', 'Ayushman Bharat Golden Card', 'csc', '🏥', 'Apply for or download your Ayushman Bharat PM-JAY Golden Card to get free health insurance cover of up to ₹5 Lakhs per year.', '["Ration Card (Patrata Parchi)","Aadhaar Card","Mobile Number linked to Aadhaar"]', '2 - 3 working days', 'https://beneficiary.nha.gov.in/', 1, '2026-08-27T19:46:42.125Z', '2026-08-27T19:46:42.125Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('c15b5306-9b50-464a-92eb-c6301f3c55be', 'pm-kisan-registration-ekyc', 'PM-Kisan Registration & eKYC', 'csc', '🌾', 'New registration for PM-Kisan Samman Nidhi Yojana and completion of mandatory biometric or OTP eKYC.', '["Land Khatauni / Land Details","Aadhaar Card","Bank Passbook","Mobile Number"]', 'Instant KYC, Approval takes 15-30 days', 'https://pmkisan.gov.in/', 1, '2026-08-27T19:46:42.128Z', '2026-08-27T19:46:42.128Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('05cd6d34-0802-44df-84d9-4639d5024df0', 'e-shram-registration-card', 'e-Shram Registration & Card', 'csc', '👷', 'Registration for unorganized sector workers to secure government scheme benefits and financial aids.', '["Aadhaar Card","Bank Account Details","Mobile Number linked to Aadhaar"]', 'Instant (15 mins)', 'https://eshram.gov.in/', 1, '2026-08-27T19:46:42.132Z', '2026-08-27T19:46:42.132Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('87c1d198-e37a-46ef-9bd2-b1ac59e0f6fc', 'voter-id-registration-card-correction', 'Voter ID Registration & Card Correction', 'digital', '🗳️', 'Apply for a new Voter ID card, transfer vote, or correct details like name, address, and age.', '["Aadhaar Card or Birth Certificate","Address Proof","1 Passport Size Photo"]', '15 - 30 working days', 'https://voters.eci.gov.in/', 1, '2026-08-27T19:46:42.134Z', '2026-08-27T19:46:42.134Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('414197de-1d75-4c52-8296-1c2b3cc6ccab', 'income-caste-domicle-certificates', 'Income, Caste & Domicle Certificates', 'digital', '📄', 'Apply for official Uttar Pradesh government certificates: Income (Aay Praman Patra), Caste (Jati Praman Patra), and Domicile (Nivas Praman Patra).', '["Self-Declaration Form","Aadhaar Card","Ration Card or Voter ID","Passport Size Photo"]', '7 - 15 working days', 'https://edistrict.up.gov.in/', 1, '2026-08-27T19:46:42.138Z', '2026-08-27T19:46:42.138Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('0192dc4a-cf10-40de-a59a-656f5b44116d', 'aeps-cash-deposit-withdrawal', 'AePS Cash Deposit & Withdrawal', 'banking', '🏦', 'Aadhaar Enabled Payment System (AePS) allowing you to withdraw, deposit, or check balance of any bank account using biometrics.', '["Aadhaar Card","Linked Bank Account","Biometric (Fingerprint) Verification"]', 'Instant', NULL, 1, '2026-08-27T19:46:42.143Z', '2026-08-27T19:46:42.143Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('9e3f6e3c-39cf-442b-bd24-7895cd27775f', 'board-university-exam-forms', 'Board & University Exam Forms', 'education', '📝', 'Professional assistance with error-free filling of UP Board, CBSE, and local university examination and admission forms.', '["Previous Year Marksheet","Passport Photo","Signature","Admit Card / Roll Number"]', 'Instant (30 mins)', NULL, 1, '2026-08-27T19:46:42.145Z', '2026-08-27T19:46:42.145Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('a12b43ab-46db-4a56-90d3-9508158ac624', 'up-pre-post-matric-scholarship', 'UP Pre/Post Matric Scholarship', 'education', '🎓', 'Apply online for government financial support for Class 9, 10, 11, 12 and university/diploma courses in Uttar Pradesh.', '["Aadhaar Card","Income, Caste & Domicile Certificates","Fee Receipt & College ID","Bank Passbook"]', '15 - 25 days (Verification pending college)', 'https://scholarship.up.gov.in/', 1, '2026-08-27T19:46:42.148Z', '2026-08-27T19:46:42.148Z');
INSERT OR IGNORE INTO Service (id, slug, name, category, icon, description, requirements, processingTime, officialLink, active, createdAt, updatedAt) VALUES ('b47d0e01-5537-44f5-aa06-c5f4a385897d', 'basic-computer-courses-training', 'Basic Computer Courses & Training', 'education', '💻', 'Learn typing, MS Office, internet skills, and digital literacy under specialized guidance at our physical computer centre.', '["Interest to Learn","Photo ID Proof"]', '1 Month to 3 Months courses', NULL, 1, '2026-08-27T19:46:42.151Z', '2026-08-27T19:46:42.151Z');
INSERT OR IGNORE INTO BlogPost (id, title, slug, summary, content, category, author, publishedDate, readTime, image, published, createdAt, updatedAt) VALUES ('53e04591-4dfe-492c-b9cc-49e5f8ec4424', 'How to Download and Print Your Smart PVC Aadhaar Card Online', 'download-print-smart-pvc-aadhaar', 'A step-by-step guide explaining how to securely download your e-Aadhaar PDF card from the UIDAI portal and print it on a wallet-sized durable plastic PVC card.', '## Introduction
The Aadhaar card is the most crucial identity document in India. Carrying the paper printout in your pocket can lead to tearing, wetting, or wear. A premium PVC smart Aadhaar card is the perfect alternative. Here is a step-by-step guide on how to print your Aadhaar on PVC.

## Step 1: Download your e-Aadhaar PDF
To print your Aadhaar, you need the official e-Aadhaar PDF file. You can download it directly from the UIDAI portal (myaadhaar.uidai.gov.in) using your Aadhaar number or Enrolment ID.

## Step 2: Ensure OTP verification
During download, UIDAI will send a one-time password (OTP) to your registered mobile number. Complete this verification to download the password-protected PDF file.

## Step 3: Order on UniqueCSCPoint
Go to our orders page, select ''Aadhaar PVC Smart Card'', enter your name and phone, upload the downloaded PDF file, specify your village/district address, and complete the ₹100 payment. We print it on a high-definition PVC card and ship it with free delivery!', 'UIDAI Guides', 'Mohd Irfak Ahmad', '24 Aug 2026', '4 mins read', '/images/pvc-aadhaar-mockup.jpg', 1, '2026-08-27T19:46:42.180Z', '2026-08-27T19:46:42.180Z');
INSERT OR IGNORE INTO BlogPost (id, title, slug, summary, content, category, author, publishedDate, readTime, image, published, createdAt, updatedAt) VALUES ('7f739d1a-3627-4ca5-b5ea-2e902ef0c749', 'Applying for Income, Caste, and Domicile Certificates in UP', 'apply-income-caste-domicile-up', 'A complete guide for citizens of Bahraich and wider Uttar Pradesh on the documents required and steps to apply for official e-District certificates.', '## Overview
Income (Aay), Caste (Jati), and Domicile (Nivas) certificates are vital documents for students applying for scholarships and citizens seeking government benefits in Uttar Pradesh. Here is how you can apply for these online.

## Documents Required
To apply, you need the following scanned copies:
- Clear passport size photo
- Aadhaar card as identity proof
- Self-Declaration Form (Swaghosna Patra)
- Ration card copy or Voter ID

## Processing Timeline
Once submitted, the files are verified by your local Lekhpal (revenue officer) and Tehsildar. The process typically takes 7 to 15 working days. You can check updates on the UP e-District site or visit our physical counter in Harchanda, Jarwal for swift execution.', 'e-District', 'Mohd Irfak Ahmad', '18 Aug 2026', '5 mins read', '/images/csc-workspace.jpg', 1, '2026-08-27T19:46:42.182Z', '2026-08-27T19:46:42.182Z');
INSERT OR IGNORE INTO Review (id, rating, content, author, location, date, approved, createdAt) VALUES ('0236cb71-736f-4584-8351-9b0b27e5e3bd', 5, 'मैंने यहाँ से अपना आधार और पैन कार्ड PVC में प्रिंट करवाया। बहुत ही बढ़िया क्वालिटी है, बिल्कुल असली ATM कार्ड जैसा दिखता है।', 'Rahul Verma', 'Jarwal Road, Bahraich', '12 Aug 2026', 1, '2026-08-27T19:46:42.172Z');
INSERT OR IGNORE INTO Review (id, rating, content, author, location, date, approved, createdAt) VALUES ('9a3dcabc-cdb6-45bd-8608-24e697396ad3', 5, 'Unique Computer Centre has excellent service! I filled my university scholarship form here. Irfak ji was very patient and made sure all details were correct.', 'Amit Kumar Yadav', 'Harchanda, Jarwal', '05 Aug 2026', 1, '2026-08-27T19:46:42.174Z');
INSERT OR IGNORE INTO Review (id, rating, content, author, location, date, approved, createdAt) VALUES ('3bfc1cf6-e09c-4feb-91cb-c1b216a7b6da', 5, 'मैंने पीएम किसान ई-केवाईसी करवाई थी। दुकान पर भीड़ होने के बावजूद उन्होंने 5 मिनट में मेरा काम कर दिया। बहुत बढ़िया व्यव्हार है।', 'Ramesh Prasad', 'Bahraich', '28 Jul 2026', 1, '2026-08-27T19:46:42.176Z');
INSERT OR IGNORE INTO Review (id, rating, content, author, location, date, approved, createdAt) VALUES ('a5dafdb0-f088-4a80-a19d-a2a7625e94cf', 5, 'मैंने यहाँ से अपना आधार और पैन कार्ड PVC में प्रिंट करवाया। बहुत ही बढ़िया क्वालिटी है, बिल्कुल असली ATM कार्ड जैसा दिखता है।', 'Rahul Verma', 'Jarwal Road, Bahraich', '12 Aug 2026', 1, '2026-08-28T06:08:02.647Z');
INSERT OR IGNORE INTO Review (id, rating, content, author, location, date, approved, createdAt) VALUES ('ed137cd8-4b75-4151-9e14-56ea7fd74bfa', 5, 'Unique Computer Centre has excellent service! I filled my university scholarship form here. Irfak ji was very patient and made sure all details were correct.', 'Amit Kumar Yadav', 'Harchanda, Jarwal', '05 Aug 2026', 1, '2026-08-28T06:08:02.653Z');
INSERT OR IGNORE INTO Review (id, rating, content, author, location, date, approved, createdAt) VALUES ('6b04b842-1222-44a7-8559-2c2bfaee0083', 5, 'मैंने पीएम किसान ई-केवाईसी करवाई थी। दुकान पर भीड़ होने के बावजूद उन्होंने 5 मिनट में मेरा काम कर दिया। बहुत बढ़िया व्यव्हार है।', 'Ramesh Prasad', 'Bahraich', '28 Jul 2026', 1, '2026-08-28T06:08:02.658Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('0f5db1c9-9f0f-404c-8104-3fd9b096a6ae', 'Main Computer Workspace Area', 'centre', '/images/csc-workspace.jpg', 'Inside view of Unique Computer Centre desktop workstations and printers', '2026-08-27T19:46:42.185Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('9520e031-0a35-4d91-8f24-5bbac052659b', 'Glossy Aadhaar PVC Smart Cards', 'pvc', '/images/pvc-aadhaar-mockup.jpg', 'Mockup print sample of Aadhaar PVC smart card with barcode details', '2026-08-27T19:46:42.187Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('2675a380-7836-4a32-9851-fbdc30241eb2', 'Mohd Irfak Ahmad at Center Desk', 'staff', '/images/founder.jpg', 'Mohd Irfak Ahmad, founder of Unique Computer Centre smiling at his desk', '2026-08-27T19:46:42.189Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('711ec10b-de6b-46e9-8640-2cc13dec19d4', 'Glossy PAN PVC Smart Cards', 'pvc', '/images/pvc-pan-mockup.jpg', 'Mockup print sample of Permanent Account Number PAN card on plastic smart card', '2026-08-27T19:46:42.192Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('296b5c51-ab42-4103-a45b-34f7c480d756', 'Main Computer Workspace Area', 'centre', '/images/csc-workspace.jpg', 'Inside view of Unique Computer Centre desktop workstations and printers', '2026-08-28T06:08:02.671Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('f5ed5ce9-7809-4a7b-a6ac-ed7a5ba27fd1', 'Glossy Aadhaar PVC Smart Cards', 'pvc', '/images/pvc-aadhaar-mockup.jpg', 'Mockup print sample of Aadhaar PVC smart card with barcode details', '2026-08-28T06:08:02.676Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('477a5884-01f9-4380-a56a-7d9fa3ef5bdf', 'Mohd Irfak Ahmad at Center Desk', 'staff', '/images/founder.jpg', 'Mohd Irfak Ahmad, founder of Unique Computer Centre smiling at his desk', '2026-08-28T06:08:02.681Z');
INSERT OR IGNORE INTO GalleryItem (id, title, category, image, alt, createdAt) VALUES ('904ff312-24a2-4f95-9d3a-5d4c9f98d2e2', 'Glossy PAN PVC Smart Cards', 'pvc', '/images/pvc-pan-mockup.jpg', 'Mockup print sample of Permanent Account Number PAN card on plastic smart card', '2026-08-28T06:08:02.686Z');
INSERT OR IGNORE INTO Setting (id, key, value, updatedAt) VALUES ('6b29d863-bbe7-4a8a-a475-e820a78c3af2', 'whatsapp_number', '918299315137', '2026-08-27T19:46:42.195Z');
INSERT OR IGNORE INTO Setting (id, key, value, updatedAt) VALUES ('ff868cbd-ae53-42d0-bf89-e93eb67b7f55', 'business_phone', '+91 82993 15137', '2026-08-27T19:46:42.198Z');
INSERT OR IGNORE INTO Setting (id, key, value, updatedAt) VALUES ('a0e02938-51e2-45fa-b42a-e2cd064dacfb', 'business_email', 'Uniquecscpoint1020@gmail.com', '2026-08-27T19:46:42.200Z');
INSERT OR IGNORE INTO Setting (id, key, value, updatedAt) VALUES ('bf401976-df9c-40b9-a0b8-93964e059623', 'business_address', 'Aryavart bank ke bagal, Harchanda, Jarwal, Bahraich (UP) 271904', '2026-08-27T19:46:42.203Z');
INSERT OR IGNORE INTO Setting (id, key, value, updatedAt) VALUES ('31635f50-66e7-4a41-8b71-49a0c740445e', 'pvc_base_price', '100', '2026-08-27T19:46:42.205Z');
